AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  OrderStatusUpdateHandler

  Sample SAM Template for OrderStatusUpdateHandler

Resources:
  OrderStatusUpdateFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: OrderStatusUpdateFunction
      CodeUri: OrderStatusUpdateLambdaFunction
      Handler: io.openmarket.order.lambda.entry.LambdaEntry::handleRequest
      Runtime: java8
      MemorySize: 512
      Timeout: 30
      Role: arn:aws:iam::185046651126:role/LambdaRole
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -Dlog4j.configurationFile=log4j2.xml
          DB_URL: your-db-url
          DB_USER: admin
          DB_PASS: password
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:us-west-2:185046651126:OnTransactionProcessed